Hw02 is completed
KaziPHone/hw-golang pull request #2
Opened 2024-06-12 20:14 UTC by KaziPHone

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-14 11:41 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако не хватает новых юнит-тестов. Возвращаю задачу на доработку

Прошу прислать инвайт в репозиторий и защитить ветку мастер от мержа без аппрува. Детали в инструкции по сдаче ДЗ

2024-06-14 11:41 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	result := ""
Для составления итоговой строки рекомендую использовать `strings.Builder`

2024-06-14 11:41 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			result += multiRune(arrV[i], arrV[i+1])
Можно использовать `strings.Repeat`

2024-06-14 11:41 UTC, agneum commented on hw02_unpack_string/go.mod
> +module github.com/kaziphone/hw02_unpack_string
Название модуля должно включать полный путь до репозитория

2024-06-15 10:17 UTC, KaziPHone commented on hw02_unpack_string/go.mod
> +module github.com/kaziphone/hw02_unpack_string
Вот тут не совсем понял! Вроде бы полный путь указан

2024-06-15 10:17 UTC, KaziPHone commented on hw02_unpack_string/unpack.go
> +			result += multiRune(arrV[i], arrV[i+1])
Поправил

2024-06-15 10:17 UTC, KaziPHone commented on hw02_unpack_string/unpack.go
> +	result := ""
Поправил

2024-06-15 10:48 UTC, KaziPHone commented
Все готово

2024-06-16 14:54 UTC, agneum approved these changes
Спасибо за тесты. Принято

2024-06-16 15:00 UTC, agneum commented on hw02_unpack_string/go.mod
> +module github.com/kaziphone/hw02_unpack_string
Здесь только пользователь и путь к пакету внутри репозитория, не хватает названия репозитория
`github.com/KaziPHone/hw-golang/hw02_unpack_string`

2024-06-16 15:04 UTC, merged